# No trajectory controllers - using position controller directly
# MoveIt will plan but not execute trajectories
controller_names: [forward_position_controller]

# controller_names:
#   - parker_linear_actuator

# # Parker linear actuator controller
# parker_linear_actuator:
#   action_ns: follow_joint_trajectory
#   type: FollowJointTrajectory
#   default: true
#   joints:
#     - linear_actuator_to_linear_actuator_plate_joint
