# Default initial positions for arpa_system's ros2_control fake system

initial_positions:
  linear_actuator_to_linear_actuator_plate_joint: 0.0
  shoulder_pan_joint: 0
  shoulder_lift_joint: 0
  elbow_joint: 0
  wrist_1_joint: 0
  wrist_2_joint: 0
  wrist_3_joint: 0